version: 2

sources:
  - name: dvp_raw
    database: dvp
    schema: raw
    tables:
      - name: raw_student_course_cohort
        description: Course cohorts purchased by the student

  - name: dvp_raw_vault
    database: dvp
    schema: raw_vault
    tables:
      - name: hub_course
        description: The entity of business course keys
      - name: hub_cohort
        description: The entity of business course cohort keys
      - name: hub_student
        description: The entity of business student keys
      - name: link_course_cohort
        description: The relationship between hub_course and hub_cohort
      - name: t_link_student_course
        description: The relationship between hub_student and hub_course
      - name: t_link_student_cohort
        description: The relationship between hub_student and hub_cohort
